# Project 9 -- Atulya Kadur

**TA Help:** John Smith, Alice Jones

- Help with figuring out how to write a function.
    
**Collaboration:** Friend1, Friend2
    
- Helped figuring out how to load the dataset.
- Helped debug error with my plot.

## Question 1

In [1]:
import pandas as pd

In [3]:
myDF = pd.read_csv('/anvil/projects/tdm/data/whin/weather.csv')

In [4]:
pd.set_option('display.max_columns', None)

In [6]:
myDF.head

<bound method NDFrame.head of         station_id   latitude  longitude              name  \
0                1  40.938940 -86.474180   WHIN001-PULA001
1                1  40.938940 -86.474180   WHIN001-PULA001
2                1  40.938940 -86.474180   WHIN001-PULA001
3                1  40.938940 -86.474180   WHIN001-PULA001
4                1  40.938940 -86.474180   WHIN001-PULA001
...            ...        ...        ...               ...
999995         171  40.296799 -87.390285  WHIN038E-WARR004
999996         171  40.296799 -87.390285  WHIN038E-WARR004
999997         171  40.296799 -87.390285  WHIN038E-WARR004
999998         171  40.296799 -87.390285  WHIN038E-WARR004
999999         171  40.296799 -87.390285  WHIN038E-WARR004

            observation_time  temperature  temperature_high  temperature_low  \
0       2019-07-10T04:00:00Z         70.0              71.0             70.0
1       2019-07-10T04:15:00Z         69.0              70.0             69.0
2       2019-07-11T04:00:00Z         76.0              77.0             76.0
3       2019-07-11T04:15:00Z         76.0              76.0             76.0
4       2019-07-11T04:30:00Z         76.0              76.0             76.0
...                      ...          ...               ...              ...
999995  2021-07-10T06:30:00Z         64.0              64.0             64.0
999996  2021-07-10T06:45:00Z         64.0              64.0             64.0
999997  2021-07-10T07:00:00Z         64.0              64.0             64.0
999998  2021-07-10T07:15:00Z         64.0              64.0             64.0
999999  2021-07-10T07:30:00Z         64.0              64.0             63.0

        humidity  solar_radiation  solar_radiation_high  rain  \
0           83.0              NaN                   NaN   0.0
1           84.0              NaN                   NaN   0.0
2           76.0              NaN                   NaN   0.0
3           77.0              NaN                   NaN   0.0
4           77.0              NaN                   NaN   0.0
...          ...              ...                   ...   ...
999995      91.0              0.0                   0.0   0.0
999996      90.0              0.0                   0.0   0.0
999997      91.0              0.0                   0.0   0.0
999998      91.0              0.0                   0.0   0.0
999999      91.0              0.0                   0.0   0.0

        rain_inches_last_hour  wind_speed_mph  wind_direction_degrees  \
0                         0.0             0.0                     NaN
1                         0.0             1.0                   247.5
2                         0.0             2.0                   202.5
3                         0.0             2.0                   202.5
4                         0.0             2.0                   225.0
...                       ...             ...                     ...
999995                    0.0             2.0                    90.0
999996                    0.0             1.0                    67.5
999997                    0.0             1.0                    67.5
999998                    0.0             0.0                    67.5
999999                    0.0             3.0                    90.0

        wind_gust_speed_mph  wind_gust_direction_degrees  pressure  \
0                       3.0                        247.5    30.050
1                       3.0                        247.5    30.040
2                       4.0                        202.5    29.890
3                       4.0                        202.5    29.880
4                       4.0                        202.5    29.880
...                     ...                          ...       ...
999995                  4.0                          NaN    30.015
999996                  4.0                         90.0    30.017
999997                  3.0                         67.5    30.016
999998                  3.0                         67.5    30.010
999999                  7.0                         67.5    29.996

        soil_temp_1  soil_temp_2  soil_temp_3  soil_temp_4  soil_moist_1  \
0              77.0         78.0         76.0         74.0          24.0
1              76.0         78.0         76.0         74.0          24.0
2              80.0         80.0         78.0         75.0          31.0
3              80.0         80.0         78.0         75.0          31.0
4              80.0         80.0         78.0         75.0          32.0
...             ...          ...          ...          ...           ...
999995          NaN          NaN          NaN          NaN           NaN
999996          NaN          NaN          NaN          NaN           NaN
999997          NaN          NaN          NaN          NaN           NaN
999998          NaN          NaN          NaN          NaN           NaN
999999          NaN          NaN          NaN          NaN           NaN

        soil_moist_2  soil_moist_3  soil_moist_4
0               24.0          10.0           9.0
1               25.0          10.0           9.0
2               30.0          12.0          10.0
3               31.0          12.0          10.0
4               31.0          12.0          10.0
...              ...           ...           ...
999995           NaN           NaN           NaN
999996           NaN           NaN           NaN
999997           NaN           NaN           NaN
999998           NaN           NaN           NaN
999999           NaN           NaN           NaN

[1000000 rows x 26 columns]>

In [9]:
#1a
myDF.value_counts('station_id')

station_id
1      71631
20     56917
147    45600
143    45593
146    45579
145    45509
144    45495
142    45395
149    44060
159    43563
153    43559
157    43534
155    42993
160    42810
156    42807
151    42806
164    38791
163    37908
166    30242
167    27463
168    18581
169    14905
172    14812
179    14772
176    14402
173    13648
175    13314
171    13311
Name: count, dtype: int64

In [10]:
#1b
myDF.groupby('station_id').size()

station_id
1      71631
20     56917
142    45395
143    45593
144    45495
145    45509
146    45579
147    45600
149    44060
151    42806
153    43559
155    42993
156    42807
157    43534
159    43563
160    42810
163    37908
164    38791
166    30242
167    27463
168    18581
169    14905
171    13311
172    14812
173    13648
175    13314
176    14402
179    14772
dtype: int64

1c: I like the first one because it makes most sense.

Markdown notes and sentences and analysis written here.

## Question 2

In [14]:
#2a
myDF.isnull().sum()

station_id                          0
latitude                            0
longitude                           0
name                                0
observation_time                    0
temperature                      4176
temperature_high                 4123
temperature_low                  4123
humidity                         4162
solar_radiation                 48104
solar_radiation_high            12828
rain                                0
rain_inches_last_hour               0
wind_speed_mph                   4032
wind_direction_degrees          95545
wind_gust_speed_mph                 0
wind_gust_direction_degrees     94216
pressure                            0
soil_temp_1                    114043
soil_temp_2                    114041
soil_temp_3                    114037
soil_temp_4                    114036
soil_moist_1                   114124
soil_moist_2                   114170
soil_moist_3                   114174
soil_moist_4                   114150
dtype: int64

In [15]:
#2b
(myDF.isnull().sum()).sum()

1184084

In [45]:
#2c
myDF_cleaned = myDF.dropna()

In [46]:
#2d: no more 😎
myDF_cleaned.isnull().sum()

station_id                     0
latitude                       0
longitude                      0
name                           0
observation_time               0
temperature                    0
temperature_high               0
temperature_low                0
humidity                       0
solar_radiation                0
solar_radiation_high           0
rain                           0
rain_inches_last_hour          0
wind_speed_mph                 0
wind_direction_degrees         0
wind_gust_speed_mph            0
wind_gust_direction_degrees    0
pressure                       0
soil_temp_1                    0
soil_temp_2                    0
soil_temp_3                    0
soil_temp_4                    0
soil_moist_1                   0
soil_moist_2                   0
soil_moist_3                   0
soil_moist_4                   0
dtype: int64

Markdown notes and sentences and analysis written here.

## Question 3

In [47]:
#3a
myDF_copy = myDF.dropna(subset=['temperature'])

In [48]:
myDF_copy.isnull().sum()

station_id                          0
latitude                            0
longitude                           0
name                                0
observation_time                    0
temperature                         0
temperature_high                    7
temperature_low                     7
humidity                            7
solar_radiation                 43989
solar_radiation_high            12825
rain                                0
rain_inches_last_hour               0
wind_speed_mph                      6
wind_direction_degrees          91427
wind_gust_speed_mph                 0
wind_gust_direction_degrees     90099
pressure                            0
soil_temp_1                    113951
soil_temp_2                    113949
soil_temp_3                    113945
soil_temp_4                    113944
soil_moist_1                   114032
soil_moist_2                   114078
soil_moist_3                   114082
soil_moist_4                   114058
dtype: int64

In [54]:
#3b
myDF_copy['location'] = myDF_copy['latitude'].astype(str) + ', ' + myDF_copy['longitude'].astype(str)

In [51]:
myDF_copy.groupby('location').head()

,station_id,latitude,longitude,name,observation_time,temperature,temperature_high,temperature_low,humidity,solar_radiation,solar_radiation_high,rain,rain_inches_last_hour,wind_speed_mph,wind_direction_degrees,wind_gust_speed_mph,wind_gust_direction_degrees,pressure,soil_temp_1,soil_temp_2,soil_temp_3,soil_temp_4,soil_moist_1,soil_moist_2,soil_moist_3,soil_moist_4,location
0,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-10T04:00:00Z,70.0,71.0,70.0,83.0,NaN,NaN,0.0,0.0,0.0,NaN,3.0,247.5,30.050,77.0,78.0,76.0,74.0,24.0,24.0,10.0,9.0,"40.93894, -86.47418"
1,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-10T04:15:00Z,69.0,70.0,69.0,84.0,NaN,NaN,0.0,0.0,1.0,247.5,3.0,247.5,30.040,76.0,78.0,76.0,74.0,24.0,25.0,10.0,9.0,"40.93894, -86.47418"
2,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-11T04:00:00Z,76.0,77.0,76.0,76.0,NaN,NaN,0.0,0.0,2.0,202.5,4.0,202.5,29.890,80.0,80.0,78.0,75.0,31.0,30.0,12.0,10.0,"40.93894, -86.47418"
3,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-11T04:15:00Z,76.0,76.0,76.0,77.0,NaN,NaN,0.0,0.0,2.0,202.5,4.0,202.5,29.880,80.0,80.0,78.0,75.0,31.0,31.0,12.0,10.0,"40.93894, -86.47418"
4,1,40.938940,-86.474180,WHIN001-PULA001,2019-07-11T04:30:00Z,76.0,76.0,76.0,77.0,NaN,NaN,0.0,0.0,2.0,225.0,4.0,202.5,29.880,80.0,80.0,78.0,75.0,32.0,31.0,12.0,10.0,"40.93894, -86.47418"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986689,171,40.296799,-87.390285,WHIN038E-WARR004,2021-02-20T20:15:00Z,31.0,31.0,31.0,62.0,582.0,599.0,0.0,0.0,6.0,157.5,11.0,157.5,30.342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"40.2967994865571, -87.3902853950858"
986690,171,40.296799,-87.390285,WHIN038E-WARR004,2021-02-20T20:30:00Z,31.0,31.0,31.0,61.0,545.0,563.0,0.0,0.0,6.0,180.0,10.0,157.5,30.339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"40.2967994865571, -87.3902853950858"
986691,171,40.296799,-87.390285,WHIN038E-WARR004,2021-02-20T20:45:00Z,31.0,31.0,31.0,61.0,512.0,527.0,0.0,0.0,6.0,157.5,10.0,157.5,30.341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"40.2967994865571, -87.3902853950858"
986692,171,40.296799,-87.390285,WHIN038E-WARR004,2021-02-20T21:00:00Z,31.0,31.0,31.0,60.0,465.0,487.0,0.0,0.0,7.0,157.5,10.0,157.5,30.330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"40.2967994865571, -87.3902853950858"
986693,171,40.296799,-87.390285,WHIN038E-WARR004,2021-02-20T21:15:00Z,31.0,31.0,31.0,61.0,422.0,439.0,0.0,0.0,7.0,157.5,10.0,157.5,30.329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"40.2967994865571, -87.3902853950858"

In [55]:
#3c
(myDF_copy.groupby('location'))['temperature'].mean()

location
40.10483, -86.86619                    56.057495
40.1492432088387, -86.7371410131454    61.413324
40.16179, -87.35246                    54.052897
40.2709571472446, -87.1486035394257    49.803342
40.2967994865571, -87.3902853950858    57.855233
40.30156, -87.48248                    58.889855
40.37634, -86.59591                    54.794076
40.38116, -86.40269                    47.765668
40.3840069271445, -87.31664031744      59.552215
40.38539, -87.51034                    55.115662
40.3861140862113, -87.1012964844704    59.383360
40.42124, -86.84642                    50.742410
40.43134, -86.53464                    55.081819
40.48079, -87.20682                    51.730032
40.4869749155437, -87.4914180859923    58.971553
40.51432, -86.45856                    55.183031
40.53722, -86.95342                    55.070667
40.5485, -87.12477                     54.898998
40.58629, -87.43654                    54.676701
40.59057, -86.39155                    55.307808
40.70178, -86.70649                    55.482287
40.78049, -86.89576                    54.791890
40.84436, -86.18173                    54.942505
40.93894, -86.47418                    49.883742
40.9700622558594, -86.9013715815608    59.919768
40.97061, -86.35304                    55.292530
40.98224, -86.38542                    54.206106
41.01865, -86.7101                     53.836086
Name: temperature, dtype: float64

Markdown notes and sentences and analysis written here.

## Question 4

In [56]:
#question 4 answer
def temperature_and_location(dataframe):
    dataframe_copy = dataframe.dropna(subset=['temperature'])
    dataframe_copy['location'] = dataframe_copy['latitude'].astype(str) + ', ' + dataframe_copy['longitude'].astype(str)
    return (dataframe_copy.groupby('location'))['temperature'].mean()
temperature_and_location(myDF_copy)

location
40.10483, -86.86619                    56.057495
40.1492432088387, -86.7371410131454    61.413324
40.16179, -87.35246                    54.052897
40.2709571472446, -87.1486035394257    49.803342
40.2967994865571, -87.3902853950858    57.855233
40.30156, -87.48248                    58.889855
40.37634, -86.59591                    54.794076
40.38116, -86.40269                    47.765668
40.3840069271445, -87.31664031744      59.552215
40.38539, -87.51034                    55.115662
40.3861140862113, -87.1012964844704    59.383360
40.42124, -86.84642                    50.742410
40.43134, -86.53464                    55.081819
40.48079, -87.20682                    51.730032
40.4869749155437, -87.4914180859923    58.971553
40.51432, -86.45856                    55.183031
40.53722, -86.95342                    55.070667
40.5485, -87.12477                     54.898998
40.58629, -87.43654                    54.676701
40.59057, -86.39155                    55.307808
40.70178, -86.70649                    55.482287
40.78049, -86.89576                    54.791890
40.84436, -86.18173                    54.942505
40.93894, -86.47418                    49.883742
40.9700622558594, -86.9013715815608    59.919768
40.97061, -86.35304                    55.292530
40.98224, -86.38542                    54.206106
41.01865, -86.7101                     53.836086
Name: temperature, dtype: float64

Markdown notes and sentences and analysis written here.

## Question 5

In [58]:
#question 3 and 4 equivalent for wind_gust_speed_mph
myDF_wind = myDF.dropna(subset=['wind_gust_speed_mph'])
myDF_wind['location'] = myDF_wind['latitude'].astype(str) + ', ' + myDF_wind['longitude'].astype(str)
(myDF_wind.groupby('location'))['wind_gust_speed_mph'].mean()

location
40.10483, -86.86619                    10.186783
40.1492432088387, -86.7371410131454    10.136323
40.16179, -87.35246                     9.026960
40.2709571472446, -87.1486035394257     9.993939
40.2967994865571, -87.3902853950858    11.560288
40.30156, -87.48248                    10.146300
40.37634, -86.59591                    10.174628
40.38116, -86.40269                    12.850781
40.3840069271445, -87.31664031744       6.184488
40.38539, -87.51034                    11.075690
40.3861140862113, -87.1012964844704     7.812415
40.42124, -86.84642                     5.973414
40.43134, -86.53464                    11.226047
40.48079, -87.20682                     6.290135
40.4869749155437, -87.4914180859923    11.720362
40.51432, -86.45856                    10.181839
40.53722, -86.95342                    11.794791
40.5485, -87.12477                     10.516033
40.58629, -87.43654                    11.681777
40.59057, -86.39155                    10.055651
40.70178, -86.70649                     9.843719
40.78049, -86.89576                    10.852191
40.84436, -86.18173                    10.285053
40.93894, -86.47418                     9.944437
40.9700622558594, -86.9013715815608    11.544695
40.97061, -86.35304                    10.564448
40.98224, -86.38542                    10.964359
41.01865, -86.7101                      8.975526
Name: wind_gust_speed_mph, dtype: float64

In [61]:
def function(dataframe):
    dataframe = myDF.dropna(subset=['wind_gust_speed_mph'])
    dataframe['location'] = dataframe['latitude'].astype(str) + ', ' + dataframe['longitude'].astype(str)
    return (myDF_wind.groupby('location'))['wind_gust_speed_mph'].mean()
function(myDF_copy)

location
40.10483, -86.86619                    10.186783
40.1492432088387, -86.7371410131454    10.136323
40.16179, -87.35246                     9.026960
40.2709571472446, -87.1486035394257     9.993939
40.2967994865571, -87.3902853950858    11.560288
40.30156, -87.48248                    10.146300
40.37634, -86.59591                    10.174628
40.38116, -86.40269                    12.850781
40.3840069271445, -87.31664031744       6.184488
40.38539, -87.51034                    11.075690
40.3861140862113, -87.1012964844704     7.812415
40.42124, -86.84642                     5.973414
40.43134, -86.53464                    11.226047
40.48079, -87.20682                     6.290135
40.4869749155437, -87.4914180859923    11.720362
40.51432, -86.45856                    10.181839
40.53722, -86.95342                    11.794791
40.5485, -87.12477                     10.516033
40.58629, -87.43654                    11.681777
40.59057, -86.39155                    10.055651
40.70178, -86.70649                     9.843719
40.78049, -86.89576                    10.852191
40.84436, -86.18173                    10.285053
40.93894, -86.47418                     9.944437
40.9700622558594, -86.9013715815608    11.544695
40.97061, -86.35304                    10.564448
40.98224, -86.38542                    10.964359
41.01865, -86.7101                      8.975526
Name: wind_gust_speed_mph, dtype: float64

Markdown notes and sentences and analysis written here.

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.